development:
  # Configure available database clients. (required)
  clients:
    # Defines the default client. (required)
    default:
      uri: <%=ENV['MONGO_URL']%>
      options:

production:
  # Configure available database clients. (required)
  clients:
    # Defines the default client. (required)
    default:
      uri: <%=ENV['MONGO_URL']%>
      options:

test:
  clients:
    default:
      database: watchheroes_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
